### ISSUE TITLE
cannot use from npm

### ISSUE THREAD

**Issue by GGAlanSmithee** [amaccann/phaser-navmesh-generation#8] opened 2017-09-24 18:57 UTC
Hi @amaccann !

First off, I'd like to say that this is a very nice plugin, even at this early stage - well done!

I'd just like to point out that there must be something wrong with your bundle. Trying to use if from npm as `import navmeshPlugin from 'phaser-namvesh-generation'` yields;

```js
demoState.js:158 Uncaught TypeError: Cannot read property 'buildFromTileLayer' of null
    at DemoState.buildNavMesh (demoState.js:158)
    at demoState.js:268
```

Steps to reproduce;

1. yarn add `phaser-navmesh-generation`
2. In your demo, at `demoState.js`, change the import to `import navmeshPlugin from 'phaser-namvesh-generation`
3. `yarn start`

Running your demo with the local build works fine BTW.

**Comment by amaccann** [comment] 2017-09-24 20:46
Hmm so @GGAlanSmithee if you have downloaded this repo, you don't need to run `yarn add...`. You should just be able to run `yarn install`, then `yarn start` to run the demo app. The demo automatically builds a dev version of the plugin you can use. 

That probably isn't clear from the repo, and maybe the demo should load a `npm` build instead

**Comment by amaccann** [comment] 2017-09-24 20:59
Out of curiousity, I ran `yarn add --dev phaser-navmesh-generation` and changed the import to:
```
import NavMeshGeneration from 'phaser-navmesh-generation';
```

It ran OK for me - looking at your issue description, there looks like a case typo: `navmeshPlugin`, as if that's all you changed, that lower-case `n` would be causing trouble further down in the code

**Comment by amaccann** [comment] 2017-09-26 17:07
Actually, yes, I can reproduce this bug: I'll look into it.

- [ ] Fix issue with `npm` package :-(

**Comment by GGAlanSmithee** [comment] 2017-09-26 17:39
@amaccaan nice that you were able to reproduce it, I meant to answer, but didn't find the time too. If I get some time, I can look into this.

**Comment by amaccann** [comment] 2017-09-27 08:25
No problem @GGAlanSmithee I've fixed the issue; it was a problem with the webpack build task. It should be working fine now after the latest `0.1.0` build deployed.

I tested on another repo and I installed  the node package fine without any problem. closing the issue

**Closed by amaccann** 2017-09-27 08:25 UTC
